language: node_js
node_js:
  - "11"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  # We need to whitelist the branches which we want to have "push" automation.
  # Pull request automation is not constrained to this set of branches.
  only:
  - master
  - alpha
  - beta
env:
  matrix:
    - CXX=g++-4.8
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "11"
      env: CXX=g++-4.8
script: yarn lint && yarn test && yarn coveralls && npx semantic-release
